### ISSUE TITLE
add google analytics

### ISSUE THREAD

**Issue by selimerunkut** [selimerunkut/cryptoson.tech#1]
<script async src="https://www.googletagmanager.com/gtag/js?id=G-YMSYYPBZWM"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-YMSYYPBZWM');
</script>

**Comment by vosaul** [comment]
v986963@gmail.com

**Comment by vosaul** [comment]
If we follow the style of the theme then it is poorly readable.
![image](https://user-images.githubusercontent.com/28349676/109826013-0c8aad00-7c43-11eb-9e27-d05265b26f16.png)
maybe better like this
![image](https://user-images.githubusercontent.com/28349676/109827020-0cd77800-7c44-11eb-8c82-0482ba2bd5ad.png)

**Comment by overqint** [comment]
yes that look definitely better
