### ISSUE TITLE
create a cookie banner compatible with GDPR & CCPA 

### ISSUE THREAD

**Issue by selimerunkut** [selimerunkut/cryptoson.tech#2]
create a cookie banner compatible with GDPR & CCPA 

example: https://jekyllcodex.org/without-plugin/cookie-consent/

**Comment by vosaul** [comment]
![image](https://user-images.githubusercontent.com/28349676/110373330-0f790980-8058-11eb-9dc7-49e3adf6360c.png)

**Comment by selimerunkut** [comment]
Thanks, can the design be like  here: 
<img width="1272" alt="Screenshot 2021-03-08 at 21 35 17" src="https://user-images.githubusercontent.com/31136147/110378770-48b07a00-8056-11eb-908d-10d534faed79.png">

**Comment by vosaul** [comment]
![image](https://user-images.githubusercontent.com/28349676/110385822-1a3b9a80-8068-11eb-9b3c-c84ca836ab05.png)
