### ISSUE TITLE
crypto ressources page

### ISSUE THREAD

**Issue by selimerunkut** [selimerunkut/cryptoson.tech#4]
If we follow the style of the theme then it is poorly readable.
![image](https://user-images.githubusercontent.com/28349676/109826013-0c8aad00-7c43-11eb-9e27-d05265b26f16.png)
maybe better like this
![image](https://user-images.githubusercontent.com/28349676/109827020-0cd77800-7c44-11eb-8c82-0482ba2bd5ad.png)

_Originally posted by @vosaul in https://github.com/overqint/cryptoson.tech/issues/1#issuecomment-789788582_

**Comment by selimerunkut** [comment]
yes that look definitely better

**Comment by vosaul** [comment]
added crypto-ressources and crypto-indicators pages and menu
