### ISSUE TITLE
add a menu/navigation 

### ISSUE THREAD

**Issue by selimerunkut** [selimerunkut/cryptoson.tech#7]
We need a navigation/menu to be able to navigate to other pages

**Comment by vosaul** [comment]
This has already been done. Let's deploy it on your Netlify so you can see all the changes online
![image](https://user-images.githubusercontent.com/28349676/109985263-3d371900-7d0d-11eb-93a6-f2130839ecf5.png)

**Comment by selimerunkut** [comment]
@vosaul Can you style the background of the navigation menu like this:

<img width="1440" alt="Screenshot 2021-03-08 at 22 39 17" src="https://user-images.githubusercontent.com/31136147/110385492-47377f80-805f-11eb-99be-47f47d2fd228.png">

**Comment by selimerunkut** [comment]
@vosaul Can you style the background of the navigation menu like this (no background):

<img width="1440" alt="Screenshot 2021-03-08 at 22 39 17" src="https://user-images.githubusercontent.com/31136147/110385492-47377f80-805f-11eb-99be-47f47d2fd228.png">
