### ISSUE TITLE
open source section and old texts are displayed, netlify cach problem?

### ISSUE THREAD

**Issue by selimerunkut** [selimerunkut/cryptoson.tech#9]
Don't know why the open source section still shows the projects of the wrong repository and still showing this for example:

<img width="269" alt="Screenshot 2021-03-05 at 00 37 37" src="https://user-images.githubusercontent.com/31136147/110045489-04b63000-7d4b-11eb-8bdf-ab2a9121d321.png">

These are not from my github:
<img width="1161" alt="Screenshot 2021-03-05 at 00 39 24" src="https://user-images.githubusercontent.com/31136147/110045658-4cd55280-7d4b-11eb-98f1-d38049176b22.png">

I think netlify cashes something and not showing the newest code

**Comment by vosaul** [comment]
you edited the data yesterday, there is an error somewhere, so the site is not updated. I will check it and fix it

**Comment by selimerunkut** [comment]
> you edited the data yesterday, there is an error somewhere, so the site is not updated. I will check it and fix it

yes I tried to fix it, but without a success

**Comment by vosaul** [comment]
I looked at the files in the morning, at first glance everything is
correct, but when assembling it gives an error. My son and I agreed to ride
in the morning, but at lunch I will be home and look more carefully

пт, 5 бер. 2021, 11:45 користувач Selim Erünkut <notifications@github.com>
пише:

**Comment by selimerunkut** [comment]
Thanks for the update, have a nice ride.
as far as getting the projects from github to the website automatically, I created an Issue in github of the template developer: 
https://github.com/longpdo/neumorphism/issues/20

**Comment by vosaul** [comment]
Hello

I fixed an error in projects.yml

Kind regards
Volodymyr Sauliak
https://sauliak.netlify.app/




пт, 5 бер. 2021 о 13:12 Selim Erünkut <notifications@github.com> пише:

**Comment by vosaul** [comment]
I set up on my account, everything works. You have an error in the settings for jekyll-github-metadata plugin somewhere

![image](https://user-images.githubusercontent.com/28349676/110142065-72f80280-7dde-11eb-95e2-9c39a94496bc.png)

**Comment by selimerunkut** [comment]
thanks, can you send me your settings for jekyll-github-metadata plugin so I can diff them and find the error

**Comment by vosaul** [comment]
it works
![image](https://user-images.githubusercontent.com/28349676/110364460-78f31b00-804c-11eb-9f9c-1969573945e4.png)

**Comment by vosaul** [comment]
But it works only with my token. 
An error with your token:
![image](https://user-images.githubusercontent.com/28349676/110365370-9ffe1c80-804d-11eb-872e-dd94c08c09d1.png)

Try to generate a new token (or edit current one), I made the following settings: 
![image](https://user-images.githubusercontent.com/28349676/110365695-fec39600-804d-11eb-9372-57854350e32f.png)
![image](https://user-images.githubusercontent.com/28349676/110365948-54983e00-804e-11eb-8b32-af4c2066edbb.png)

**Comment by selimerunkut** [comment]
Thanks, also the token was removed last time, see: https://github.com/longpdo/neumorphism/issues/20

Where do I put it exactly?

**Comment by selimerunkut** [comment]
> Thanks, also the token was removed last time, see: [longpdo/neumorphism#20](https://github.com/longpdo/neumorphism/issues/20)
> 
> Where do I put it exactly?

put it into environment-variables in netlify and it work
https://docs.netlify.com/configure-builds/environment-variables/
